# fly.toml app configuration file generated for p-ranked on 2023-11-07T17:32:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "p-ranked"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
