# Test your FastAPI endpoints

POST http://127.0.0.1:8000/games/submit
Content-Type: application/json

{
    "winner_id": 1,
    "loser_id": 2
}

###

GET http://127.0.0.1:8000/games
Accept: application/json


